[phases.setup]
nixPkgs = ["python313", "gcc", "libpq"]

[phases.install]
cmds = ["pip install -r requirements/prod.txt"]

# Pas de [start] ici — on laisse le Procfile gérer le démarrage
# collectstatic + migrate sont dans le Procfile pour avoir acces aux variables Railway
