services:
  - type: web
    name: ndiarama-backend
    env: python
    plan: free
    buildCommand: >
      pip install -r requirements/prod.txt &&
      python manage.py collectstatic --no-input &&
      python manage.py migrate
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "ndiarama-backend.onrender.com"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "False"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://ndiarama.vercel.app"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://ndiarama-backend.onrender.com"
      - key: SECURE_SSL_REDIRECT
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: ndiarama-db
          property: connectionString
      - key: DEFAULT_FROM_EMAIL
        value: "no-reply@ndiarama.com"
      - key: CONTACT_EMAIL
        value: "contact@ndiarama.com"
      - key: LOG_LEVEL
        value: "INFO"
      - key: PYTHON_VERSION
        value: "3.11.0"

databases:
  - name: ndiarama-db
    plan: free
    databaseName: ndiarama
    user: ndiarama_user