# Generated by Django 5.1.7 on 2026-04-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='mailchimp_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
