# Generated by Django 5.1.7 on 2026-04-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='apple_podcast_url',
            field=models.URLField(blank=True, help_text="Lien direct vers l'épisode Apple Podcasts"),
        ),
        migrations.AddField(
            model_name='episode',
            name='spotify_url',
            field=models.URLField(blank=True, help_text="Lien direct vers l'épisode Spotify"),
        ),
        migrations.AddField(
            model_name='episode',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text="Miniature de l'épisode (optionnel, sinon auto depuis YouTube)", null=True, upload_to='episodes/thumbnails/'),
        ),
        migrations.AddField(
            model_name='episode',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='URL complète YouTube ex: https://www.youtube.com/watch?v=abc123'),
        ),
        migrations.AddField(
            model_name='show',
            name='apple_podcast_url',
            field=models.URLField(blank=True, help_text='Lien vers Apple Podcasts'),
        ),
        migrations.AddField(
            model_name='show',
            name='spotify_show_url',
            field=models.URLField(blank=True, help_text='Lien vers le show Spotify'),
        ),
        migrations.AddField(
            model_name='show',
            name='youtube_channel_url',
            field=models.URLField(blank=True, help_text='Lien vers la chaîne YouTube ex: https://youtube.com/@ndiarama'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.CharField(blank=True, help_text="Durée lisible ex: '12:30' ou '25 min'.", max_length=20),
        ),
        migrations.AlterField(
            model_name='episode',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="À mettre en avant sur la page d'accueil."),
        ),
        migrations.AlterField(
            model_name='episode',
            name='media_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('both', 'Vidéo + Audio')], max_length=10),
        ),
        migrations.AlterField(
            model_name='episode',
            name='media_url',
            field=models.URLField(blank=True, help_text='Lien Spotify ou fichier audio hébergé.'),
        ),
    ]
